### ISSUE TITLE
Error on installation?

### ISSUE THREAD

**Issue by supporto-wifiproject** [Qengineering/Paddle-Raspberry-Pi#3]
I follow your guide to install paddle on Pi 4 (https://qengineering.eu/install-paddlepaddle-on-raspberry-pi-4.html)
After the installation, you say in order to check if everything is ok, to launch
`python3
import paddle.fluid as pd`
At this point a get this error 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.9/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/proto/framework_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/pi/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
`

**Comment by Qengineering** [comment]
@supporto-wifiproject 

TensorFlow has the same issue. Please [see here](https://github.com/Qengineering/TensorFlow-Raspberry-Pi_64-bit#tensorflow-2100) for the solution.

**Comment by supporto-wifiproject** [comment]
Thanks, I went a stewp further...
Now the error is
`Error: Can not import noavx core while this file exists: /usr/local/lib/python3.9/dist-packages/paddle/fluid/core_noavx.so`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/__init__.py", line 25, in <module>`
`    from .framework import monkey_patch_variable`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/framework/__init__.py", line 17, in <module>`
`    from . import random  # noqa: F401`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/framework/random.py", line 16, in <module>`
`    import paddle.fluid as fluid`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/__init__.py", line 36, in <module>`
`    from . import framework`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/framework.py", line 37, in <module>`
`    from . import core`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/core.py", line 366, in <module>`
`    raise e`
`  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/core.py", line 314, in <module>`
`    from . import core_noavx`
`ImportError: /usr/local/lib/python3.9/dist-packages/paddle/fluid/core_noavx.so: undefined symbol: shm_unlink`

Now what have I to do?
Thanks

**Comment by Qengineering** [comment]
Could you test the installation with [this line](https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/linux-pip_en.html#verify-installation)?

**Comment by supporto-wifiproject** [comment]
I got the same error as described in https://github.com/PaddlePaddle/Paddle/issues/44621
and if I luanch `cat /proc/cpuinfo | grep -i avx ` I get no output

**Comment by Qengineering** [comment]
AVX are Intel registers not found in ARM cores.
I will look into the issue by building PaddlePaddle from scratch here at the office.
It will take me a day or two before everything is tested. Please be patient.

**Comment by supporto-wifiproject** [comment]
I'm triyng to do the same thing following your guide to compile from scratch

**Comment by Qengineering** [comment]
I'm installing the latest version 2.4

**Comment by supporto-wifiproject** [comment]
Could you send me the url to download it?

**Comment by Qengineering** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/linux-compile_en.html
and the latest GitHub repo

**Comment by supporto-wifiproject** [comment]
Sorry for the question. I'm installing Paddle to install PaddleOCR-Lite-Document (https://github.com/Qengineering/PaddleOCR-Lite-Document). Is it better to install Paddle Lite?

**Comment by Qengineering** [comment]
That make a HUGE difference!!!
Paddle and Paddle-Lite are completely different framworks.
Forget Paddle, and install Paddle-Lite instead according the instructions found on the github repo

**Comment by supporto-wifiproject** [comment]
Thanks a lot (and sorry). I'll finish to compile paddle just for check if form scratch it works. Then I'll move to Paddle-Lite

**Comment by supporto-wifiproject** [comment]
I got an error in making phase (just FYI):

[ 42%] Building CXX object gloo/CMakeFiles/gloo.dir/common/linux.cc.o
In file included from /home/pi/Paddle/build/third_party/gloo/src/extern_gloo/gloo/common/linux.cc:15:
/usr/include/linux/ethtool.h: In function ‘int gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)’:
/usr/include/linux/ethtool.h:2147:8: error: flexible array member ‘ethtool_link_settings::link_mode_masks’ not at end of ‘struct gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed>’
 2147 |  __u32 link_mode_masks[];
      |        ^~~~~~~~~~~~~~~
/home/pi/Paddle/build/third_party/gloo/src/extern_gloo/gloo/common/linux.cc:192:11: note: next member ‘__u32 gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed struct>::link_mode_data [381]’ declared here
  192 |     __u32 link_mode_data[link_mode_data_nwords];
      |           ^~~~~~~~~~~~~~
/home/pi/Paddle/build/third_party/gloo/src/extern_gloo/gloo/common/linux.cc:190:10: note: in the definition of ‘struct gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed>’
  190 |   struct {
      |          ^
make[5]: *** [gloo/CMakeFiles/gloo.dir/build.make:264: gloo/CMakeFiles/gloo.dir/common/linux.cc.o] Errore 1
make[4]: *** [CMakeFiles/Makefile2:214: gloo/CMakeFiles/gloo.dir/all] Errore 2
make[3]: *** [Makefile:149: all] Errore 2
make[2]: *** [CMakeFiles/extern_gloo.dir/build.make:131: third_party/gloo/src/extern_gloo-stamp/extern_gloo-build] Errore 2
make[1]: *** [CMakeFiles/Makefile2:4890: CMakeFiles/extern_gloo.dir/all] Errore 2
make: *** [Makefile:149: all] Errore 2

**Comment by luisb1393** [comment]
> 

same issue when trying to build. Has anybody found a solution yet?

**Comment by luisb1393** [comment]
> AVX are Intel registers not found in ARM cores. I will look into the issue by building PaddlePaddle from scratch here at the office. It will take me a day or two before everything is tested. Please be patient.

When building in my case I get a gloo error. Did you find a solution for this?

**Comment by Qengineering** [comment]
Updated repo with the latest: `paddlepaddle-2.4.2-cp39-cp39-linux_aarch64.whl`

**Comment by luisb1393** [comment]
> Updated repo with the latest: `paddlepaddle-2.4.2-cp39-cp39-linux_aarch64.whl`

Awesome, thanks mate! Now I have PaddlePaddle with PaddleOCR working in my RPI.

**Comment by Qengineering** [comment]
@luisb1393,

Please note [a faster RPi PaddleOCR solution](https://github.com/Qengineering/PaddleOCR-Lite-Document).
